/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    pullQuote: PullQuoteBlock;
    factBox: FactBoxBlock;
    dataCallout: DataCalloutBlock;
    documentExcerpt: DocumentExcerptBlock;
    verificationNote: VerificationNoteBlock;
    employerResponse: EmployerResponseBlock;
    correctionNotice: CorrectionNoticeBlock;
  };
  collections: {
    users: User;
    articles: Article;
    pages: Page;
    topics: Topic;
    tags: Tag;
    'public-bylines': PublicByline;
    media: Media;
    submissions: Submission;
    'protected-sources': ProtectedSource;
    'protected-source-files': ProtectedSourceFile;
    'newsletter-subscriptions': NewsletterSubscription;
    corrections: Correction;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'public-bylines': PublicBylinesSelect<false> | PublicBylinesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    'protected-sources': ProtectedSourcesSelect<false> | ProtectedSourcesSelect<true>;
    'protected-source-files': ProtectedSourceFilesSelect<false> | ProtectedSourceFilesSelect<true>;
    'newsletter-subscriptions': NewsletterSubscriptionsSelect<false> | NewsletterSubscriptionsSelect<true>;
    corrections: CorrectionsSelect<false> | CorrectionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PullQuoteBlock".
 */
export interface PullQuoteBlock {
  quote: string;
  attribution?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pullQuote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FactBoxBlock".
 */
export interface FactBoxBlock {
  heading: string;
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'factBox';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DataCalloutBlock".
 */
export interface DataCalloutBlock {
  label: string;
  value: string;
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dataCallout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DocumentExcerptBlock".
 */
export interface DocumentExcerptBlock {
  sourceLabel: string;
  excerpt: string;
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'documentExcerpt';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VerificationNoteBlock".
 */
export interface VerificationNoteBlock {
  heading?: string | null;
  text: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'verificationNote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmployerResponseBlock".
 */
export interface EmployerResponseBlock {
  status: 'requested' | 'received' | 'declined' | 'no-response';
  text?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'employerResponse';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CorrectionNoticeBlock".
 */
export interface CorrectionNoticeBlock {
  date: string;
  text: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'correctionNotice';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  roles: ('owner' | 'editor' | 'reviewer' | 'source_manager' | 'newsletter_editor')[];
  active: boolean;
  lastLogin?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  internalTitle: string;
  publicHeadline: string;
  slug: string;
  subtitle?: string | null;
  format: 'inside-work' | 'expert-analysis' | 'reported-essay' | 'explainer' | 'response' | 'editorial';
  primaryTopic: string | Topic;
  additionalTopics?: (string | Topic)[] | null;
  tags?: (string | Tag)[] | null;
  publicByline: string | PublicByline;
  authorshipType: 'named' | 'verified-anonymous';
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  heroImage?: (string | null) | Media;
  heroImageCaption?: string | null;
  heroImageCredit?: string | null;
  socialImage?: (string | null) | Media;
  /**
   * Required for verified anonymous articles.
   */
  verificationStatement?: string | null;
  verificationIndicators?:
    | (
        | 'identity-verified'
        | 'employment-verified'
        | 'role-verified'
        | 'direct-knowledge-verified'
        | 'supporting-records-reviewed'
        | 'corroborated'
      )[]
    | null;
  evidenceNote?: string | null;
  employerResponseStatus?: ('not-requested' | 'requested' | 'received' | 'declined' | 'no-response') | null;
  employerResponseContent?: string | null;
  employerResponseDate?: string | null;
  relatedArticles?: (string | Article)[] | null;
  essentialReadingEligible?: boolean | null;
  insideWorkEligible?: boolean | null;
  publicationDate?: string | null;
  scheduledPublicationDate?: string | null;
  updatedDate?: string | null;
  correctionRecords?:
    | {
        date: string;
        type?: ('correction' | 'clarification' | 'update') | null;
        text: string;
        materialChange?: boolean | null;
        id?: string | null;
      }[]
    | null;
  corrections?: (string | Correction)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  editorialStage:
    | 'pitch'
    | 'under-review'
    | 'accepted'
    | 'editing'
    | 'verification'
    | 'employer-response-requested'
    | 'final-review'
    | 'scheduled'
    | 'published'
    | 'updated'
    | 'rejected'
    | 'withdrawn';
  assignedEditor?: (string | null) | User;
  internalEditorialNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: string;
  name: string;
  slug: string;
  shortDescription: string;
  longIntroduction?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  showInNavigation?: boolean | null;
  displayOrder: number;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  altText: string;
  caption?: string | null;
  credit?: string | null;
  copyrightOrLicense?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    article?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    social?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-bylines".
 */
export interface PublicByline {
  id: string;
  displayName: string;
  slug: string;
  authorshipType: 'named' | 'verified-anonymous';
  shortBiography?: string | null;
  longBiography?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  portrait?: (string | null) | Media;
  /**
   * Public only when approved for attribution.
   */
  organization?: string | null;
  relevantExpertise?: string | null;
  /**
   * Reusable wording editors may adapt on individual articles.
   */
  verificationWording?: string | null;
  publishedArticles?: (string | Article)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corrections".
 */
export interface Correction {
  id: string;
  article: string | Article;
  publicCorrectionText: string;
  correctionType: 'correction' | 'clarification' | 'update';
  date: string;
  editor: string | User;
  materialChange?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  template: 'standard' | 'policy' | 'topic-landing' | 'submission' | 'contact';
  intro?: string | null;
  contentBlocks?: (TextSectionBlock | CalloutBlock | LinkListBlock)[] | null;
  hero?: {
    kicker?: string | null;
    image?: (string | null) | Media;
    caption?: string | null;
  };
  showInNavigation?: boolean | null;
  scheduledPublicationDate?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextSectionBlock".
 */
export interface TextSectionBlock {
  heading?: string | null;
  body: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock".
 */
export interface CalloutBlock {
  label?: string | null;
  text: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkListBlock".
 */
export interface LinkListBlock {
  heading: string;
  links: {
    label: string;
    url: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'linkList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: string;
  referenceNumber: string;
  submissionType: 'pitch' | 'draft' | 'confidential-info' | 'response';
  contributorName?: string | null;
  needsAnonymity?: boolean | null;
  pseudonym?: string | null;
  personalEmail: string;
  contactPreference?: ('email' | 'phone' | 'secure-follow-up') | null;
  currentOrFormerEmployee: 'current' | 'former' | 'contractor' | 'other-direct-role' | 'not-applicable';
  organization?: string | null;
  generalRole: string;
  proposedHeadline?: string | null;
  additionalContext?: string | null;
  whatReadersShouldUnderstand?: string | null;
  personallyObserved?: string | null;
  publicInterestExplanation?: string | null;
  anonymityReason?: string | null;
  evidenceAvailability: 'none' | 'describe' | 'may-share-later';
  namedIndividualsImplicated?: boolean | null;
  activeDisputeOrLitigation?: boolean | null;
  completeDraft?: string | null;
  status:
    | 'new'
    | 'screening'
    | 'follow-up-requested'
    | 'under-review'
    | 'accepted'
    | 'declined'
    | 'converted-to-article'
    | 'closed';
  assignedEditor?: (string | null) | User;
  internalNotes?: string | null;
  submissionDate: string;
  consents: {
    privacyAcknowledged: boolean;
    notWorkDeviceAcknowledged: boolean;
    noPersonalDataAcknowledged: boolean;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "protected-sources".
 */
export interface ProtectedSource {
  id: string;
  sourceCode: string;
  legalName: string;
  preferredName?: string | null;
  personalEmail: string;
  personalTelephone?: string | null;
  employer: string;
  exactPosition: string;
  employmentStatus: 'current' | 'former' | 'contractor' | 'other';
  identityVerificationMethod?: string | null;
  employmentVerificationMethod?: string | null;
  riskNotes?: string | null;
  anonymityRequestReasoning?: string | null;
  potentialConflicts?: string | null;
  relatedArticles?: (string | Article)[] | null;
  assignedSourceManager: string | User;
  retentionOrDeletionDate?: string | null;
  consentRecords?: string | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "protected-source-files".
 */
export interface ProtectedSourceFile {
  id: string;
  source: string | ProtectedSource;
  category: 'identity-documentation' | 'employment-verification' | 'supporting-material' | 'interview-notes' | 'other';
  originalFilename?: string | null;
  accessNotes?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscriptions".
 */
export interface NewsletterSubscription {
  id: string;
  email: string;
  status: 'active' | 'unsubscribed' | 'bounced';
  consentTimestamp: string;
  sourcePage?: string | null;
  unsubscribedDate?: string | null;
  verificationToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'topics';
        value: string | Topic;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'public-bylines';
        value: string | PublicByline;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'submissions';
        value: string | Submission;
      } | null)
    | ({
        relationTo: 'protected-sources';
        value: string | ProtectedSource;
      } | null)
    | ({
        relationTo: 'protected-source-files';
        value: string | ProtectedSourceFile;
      } | null)
    | ({
        relationTo: 'newsletter-subscriptions';
        value: string | NewsletterSubscription;
      } | null)
    | ({
        relationTo: 'corrections';
        value: string | Correction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  active?: T;
  lastLogin?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  internalTitle?: T;
  publicHeadline?: T;
  slug?: T;
  subtitle?: T;
  format?: T;
  primaryTopic?: T;
  additionalTopics?: T;
  tags?: T;
  publicByline?: T;
  authorshipType?: T;
  body?: T;
  heroImage?: T;
  heroImageCaption?: T;
  heroImageCredit?: T;
  socialImage?: T;
  verificationStatement?: T;
  verificationIndicators?: T;
  evidenceNote?: T;
  employerResponseStatus?: T;
  employerResponseContent?: T;
  employerResponseDate?: T;
  relatedArticles?: T;
  essentialReadingEligible?: T;
  insideWorkEligible?: T;
  publicationDate?: T;
  scheduledPublicationDate?: T;
  updatedDate?: T;
  correctionRecords?:
    | T
    | {
        date?: T;
        type?: T;
        text?: T;
        materialChange?: T;
        id?: T;
      };
  corrections?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  editorialStage?: T;
  assignedEditor?: T;
  internalEditorialNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  template?: T;
  intro?: T;
  contentBlocks?:
    | T
    | {
        textSection?: T | TextSectionBlockSelect<T>;
        callout?: T | CalloutBlockSelect<T>;
        linkList?: T | LinkListBlockSelect<T>;
      };
  hero?:
    | T
    | {
        kicker?: T;
        image?: T;
        caption?: T;
      };
  showInNavigation?: T;
  scheduledPublicationDate?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextSectionBlock_select".
 */
export interface TextSectionBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock_select".
 */
export interface CalloutBlockSelect<T extends boolean = true> {
  label?: T;
  text?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkListBlock_select".
 */
export interface LinkListBlockSelect<T extends boolean = true> {
  heading?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortDescription?: T;
  longIntroduction?: T;
  image?: T;
  showInNavigation?: T;
  displayOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-bylines_select".
 */
export interface PublicBylinesSelect<T extends boolean = true> {
  displayName?: T;
  slug?: T;
  authorshipType?: T;
  shortBiography?: T;
  longBiography?: T;
  portrait?: T;
  organization?: T;
  relevantExpertise?: T;
  verificationWording?: T;
  publishedArticles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  altText?: T;
  caption?: T;
  credit?: T;
  copyrightOrLicense?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        article?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        social?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  referenceNumber?: T;
  submissionType?: T;
  contributorName?: T;
  needsAnonymity?: T;
  pseudonym?: T;
  personalEmail?: T;
  contactPreference?: T;
  currentOrFormerEmployee?: T;
  organization?: T;
  generalRole?: T;
  proposedHeadline?: T;
  additionalContext?: T;
  whatReadersShouldUnderstand?: T;
  personallyObserved?: T;
  publicInterestExplanation?: T;
  anonymityReason?: T;
  evidenceAvailability?: T;
  namedIndividualsImplicated?: T;
  activeDisputeOrLitigation?: T;
  completeDraft?: T;
  status?: T;
  assignedEditor?: T;
  internalNotes?: T;
  submissionDate?: T;
  consents?:
    | T
    | {
        privacyAcknowledged?: T;
        notWorkDeviceAcknowledged?: T;
        noPersonalDataAcknowledged?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "protected-sources_select".
 */
export interface ProtectedSourcesSelect<T extends boolean = true> {
  sourceCode?: T;
  legalName?: T;
  preferredName?: T;
  personalEmail?: T;
  personalTelephone?: T;
  employer?: T;
  exactPosition?: T;
  employmentStatus?: T;
  identityVerificationMethod?: T;
  employmentVerificationMethod?: T;
  riskNotes?: T;
  anonymityRequestReasoning?: T;
  potentialConflicts?: T;
  relatedArticles?: T;
  assignedSourceManager?: T;
  retentionOrDeletionDate?: T;
  consentRecords?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "protected-source-files_select".
 */
export interface ProtectedSourceFilesSelect<T extends boolean = true> {
  source?: T;
  category?: T;
  originalFilename?: T;
  accessNotes?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscriptions_select".
 */
export interface NewsletterSubscriptionsSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  consentTimestamp?: T;
  sourcePage?: T;
  unsubscribedDate?: T;
  verificationToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corrections_select".
 */
export interface CorrectionsSelect<T extends boolean = true> {
  article?: T;
  publicCorrectionText?: T;
  correctionType?: T;
  date?: T;
  editor?: T;
  materialChange?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  leadMode: 'automatic' | 'curated';
  curatedLeadArticle?: (string | null) | Article;
  secondaryArticleOverrides?: (string | Article)[] | null;
  insideWorkOverrides?: (string | Article)[] | null;
  essentialReading?: (string | Article)[] | null;
  introductoryCopy?: string | null;
  newsletterCopy?: {
    heading?: string | null;
    description?: string | null;
  };
  topicDisplayList?: (string | Topic)[] | null;
  announcement?: {
    visible?: boolean | null;
    text?: string | null;
    url?: string | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  publicationName: string;
  tagline: string;
  description: string;
  contactEmail: string;
  logoSettings?: {
    wordmarkText?: string | null;
    logo?: (string | null) | Media;
  };
  socialAccounts?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  defaultSocialImage?: (string | null) | Media;
  defaultSEO?: {
    title?: string | null;
    description?: string | null;
  };
  footerCopy?: string | null;
  newsletterSettings?: {
    enabled?: boolean | null;
    consentText?: string | null;
  };
  copyrightNotice?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  primaryNavigation?:
    | {
        label: string;
        href: string;
        order: number;
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  footerNavigation?:
    | {
        groupLabel: string;
        links: {
          label: string;
          href: string;
          order: number;
          visible?: boolean | null;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  leadMode?: T;
  curatedLeadArticle?: T;
  secondaryArticleOverrides?: T;
  insideWorkOverrides?: T;
  essentialReading?: T;
  introductoryCopy?: T;
  newsletterCopy?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  topicDisplayList?: T;
  announcement?:
    | T
    | {
        visible?: T;
        text?: T;
        url?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  publicationName?: T;
  tagline?: T;
  description?: T;
  contactEmail?: T;
  logoSettings?:
    | T
    | {
        wordmarkText?: T;
        logo?: T;
      };
  socialAccounts?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  defaultSocialImage?: T;
  defaultSEO?:
    | T
    | {
        title?: T;
        description?: T;
      };
  footerCopy?: T;
  newsletterSettings?:
    | T
    | {
        enabled?: T;
        consentText?: T;
      };
  copyrightNotice?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  primaryNavigation?:
    | T
    | {
        label?: T;
        href?: T;
        order?: T;
        visible?: T;
        id?: T;
      };
  footerNavigation?:
    | T
    | {
        groupLabel?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              order?: T;
              visible?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'articles';
          value: string | Article;
        } | null)
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}